#!/usr/bin/env python3
"""
Clips OS shared report utilities.

Common functions for generating HTML reports across all Clips OS skills.
Import from skill-specific report generators to ensure consistent styling.
"""

import base64
import math
import os
from pathlib import Path


def encode_image(image_path: str) -> str:
    """Encode an image file to base64 data URI."""
    if not image_path or not os.path.exists(image_path):
        return ""
    ext = Path(image_path).suffix.lower()
    mime = {
        "png": "image/png",
        "jpg": "image/jpeg",
        "jpeg": "image/jpeg",
        "webp": "image/webp",
    }.get(ext.lstrip("."), "image/png")
    with open(image_path, "rb") as f:
        data = base64.b64encode(f.read()).decode("utf-8")
    return f"data:{mime};base64,{data}"


def score_color(score: float) -> str:
    """Return a CSS color based on 1-5 score."""
    if score >= 4.5:
        return "#16a34a"  # green
    elif score >= 3.5:
        return "#65a30d"  # lime
    elif score >= 2.5:
        return "#ca8a04"  # amber
    elif score >= 1.5:
        return "#ea580c"  # orange
    else:
        return "#dc2626"  # red


def score_label(score: float) -> str:
    """Return a text label for a 1-5 score."""
    if score >= 4.5:
        return "Excellent"
    elif score >= 3.5:
        return "Good"
    elif score >= 2.5:
        return "Acceptable"
    elif score >= 1.5:
        return "Needs Work"
    else:
        return "Critical"


def priority_color(priority: str) -> str:
    """Return a CSS color for P0-P3 priority."""
    return {
        "P0": "#dc2626",
        "P1": "#ea580c",
        "P2": "#ca8a04",
        "P3": "#65a30d",
    }.get(priority, "#6b7280")


def priority_label(priority: str) -> str:
    """Return a text label for P0-P3 priority."""
    return {
        "P0": "Critical",
        "P1": "High",
        "P2": "Medium",
        "P3": "Low",
    }.get(priority, priority)


def lens_icon(lens: str) -> str:
    """Return a unicode icon for LIFT model lenses."""
    return {
        "clarity": "&#128269;",
        "relevance": "&#127919;",
        "friction": "&#9888;&#65039;",
        "anxiety": "&#128274;",
        "urgency": "&#9201;",
        "technical": "&#9881;&#65039;",
    }.get(lens, "&#128300;")


def report_header_html(title: str, meta_line: str, overall_score: float, pages_count: int, findings_count: int) -> str:
    """Generate the standard Clips OS report header HTML."""
    sc = score_color(overall_score)
    sl = score_label(overall_score)
    return f"""<header>
        <h1>{title}</h1>
        <div class="meta">{meta_line}</div>
        <div class="overall-score">
            <span class="big-score" style="color:{sc};">{overall_score:.1f}<span style="font-size:1.2rem;opacity:0.7;">/5</span></span>
            <div class="score-context">
                <strong>Overall Score</strong><br>
                {sl} — {pages_count} pages analyzed, {findings_count} findings
            </div>
        </div>
    </header>"""


def report_footer_html(skill_name: str) -> str:
    """Generate the standard Clips OS report footer HTML."""
    return f"""<footer>
        <p>Generated by Clips OS {skill_name} &bull; Framework: LIFT Model + Baymard Heuristics &bull; Scoring: 1-5 scale</p>
        <p>Scores reflect analysis at time of audit. Results may vary with traffic source, user segment, and device.</p>
    </footer>"""


def svg_score_gauge(score: float, size: int = 120, light_track: bool = False) -> str:
    """Generate an SVG circular gauge for a 1-5 score."""
    radius = (size - 12) / 2
    cx = cy = size / 2
    circumference = 2 * math.pi * radius
    pct = max(0, min(score, 5)) / 5
    offset = circumference * (1 - pct)
    color = score_color(score)
    track = "rgba(255,255,255,0.15)" if not light_track else "#e5e7eb"
    return f'''<svg width="{size}" height="{size}" viewBox="0 0 {size} {size}">
  <circle cx="{cx}" cy="{cy}" r="{radius}" fill="none" stroke="{track}" stroke-width="10" />
  <circle cx="{cx}" cy="{cy}" r="{radius}" fill="none" stroke="{color}" stroke-width="10"
    stroke-linecap="round" stroke-dasharray="{circumference:.1f}" stroke-dashoffset="{offset:.1f}"
    transform="rotate(-90 {cx} {cy})" class="gauge-arc" />
  <text x="{cx}" y="{cy - 4}" text-anchor="middle" font-size="{size * 0.28:.0f}" font-weight="800" fill="{'white' if not light_track else color}">{score:.1f}</text>
  <text x="{cx}" y="{cy + size * 0.14:.0f}" text-anchor="middle" font-size="{size * 0.12:.0f}" fill="{'rgba(255,255,255,0.7)' if not light_track else '#6b7280'}">/5 &middot; {score_label(score)}</text>
</svg>'''


def svg_score_ring(score: float, size: int = 20) -> str:
    """Generate a tiny SVG score ring for navigation pills."""
    radius = (size - 4) / 2
    cx = cy = size / 2
    circumference = 2 * math.pi * radius
    pct = max(0, min(score, 5)) / 5
    offset = circumference * (1 - pct)
    color = score_color(score)
    return f'''<svg width="{size}" height="{size}" viewBox="0 0 {size} {size}" style="vertical-align:middle;">
  <circle cx="{cx}" cy="{cy}" r="{radius}" fill="none" stroke="#e5e7eb" stroke-width="2.5" />
  <circle cx="{cx}" cy="{cy}" r="{radius}" fill="none" stroke="{color}" stroke-width="2.5"
    stroke-linecap="round" stroke-dasharray="{circumference:.1f}" stroke-dashoffset="{offset:.1f}"
    transform="rotate(-90 {cx} {cy})" />
</svg>'''


def svg_score_bar(score: float, width: int = 80) -> str:
    """Generate an inline SVG horizontal progress bar for a 1-5 score."""
    pct = max(0, min(score, 5)) / 5
    fill_w = pct * width
    color = score_color(score)
    return f'''<svg width="{width}" height="8" viewBox="0 0 {width} 8" style="vertical-align:middle;">
  <rect x="0" y="0" width="{width}" height="8" rx="4" fill="#e5e7eb" />
  <rect x="0" y="0" width="{fill_w:.1f}" height="8" rx="4" fill="{color}" />
</svg>'''


def svg_priority_donut(priority_counts: dict, size: int = 100) -> str:
    """Generate an SVG donut chart for P0-P3 priority distribution."""
    total = sum(priority_counts.values())
    if total == 0:
        return ""
    radius = (size - 12) / 2
    cx = cy = size / 2
    circumference = 2 * math.pi * radius
    segments = []
    cumulative = 0
    for p in ["P0", "P1", "P2", "P3"]:
        count = priority_counts.get(p, 0)
        if count == 0:
            continue
        pct = count / total
        dash = circumference * pct
        gap = circumference - dash
        offset = -circumference * cumulative
        color = priority_color(p)
        segments.append(
            f'<circle cx="{cx}" cy="{cy}" r="{radius}" fill="none" stroke="{color}" stroke-width="10"'
            f' stroke-dasharray="{dash:.1f} {gap:.1f}" stroke-dashoffset="{offset:.1f}"'
            f' transform="rotate(-90 {cx} {cy})" />'
        )
        cumulative += pct

    legend = ""
    for p in ["P0", "P1", "P2", "P3"]:
        count = priority_counts.get(p, 0)
        if count == 0:
            continue
        color = priority_color(p)
        legend += f'<span style="display:inline-flex;align-items:center;gap:4px;margin-right:12px;font-size:0.8rem;"><span style="width:8px;height:8px;border-radius:50%;background:{color};display:inline-block;"></span>{p}: {count}</span>'

    return f'''<div style="text-align:center;">
  <svg width="{size}" height="{size}" viewBox="0 0 {size} {size}">
    {"".join(segments)}
    <text x="{cx}" y="{cy + 1}" text-anchor="middle" font-size="{size * 0.22:.0f}" font-weight="700" fill="#334155">{total}</text>
    <text x="{cx}" y="{cy + size * 0.14:.0f}" text-anchor="middle" font-size="{size * 0.1:.0f}" fill="#6b7280">findings</text>
  </svg>
  <div style="margin-top:8px;">{legend}</div>
</div>'''
