#!/usr/bin/env python3
"""
Clips OS shared report utilities.

Common functions for generating HTML reports across all Clips OS skills.
Import from skill-specific report generators to ensure consistent styling.
"""

import base64
import os
from pathlib import Path


def encode_image(image_path: str) -> str:
    """Encode an image file to base64 data URI."""
    if not image_path or not os.path.exists(image_path):
        return ""
    ext = Path(image_path).suffix.lower()
    mime = {
        "png": "image/png",
        "jpg": "image/jpeg",
        "jpeg": "image/jpeg",
        "webp": "image/webp",
    }.get(ext.lstrip("."), "image/png")
    with open(image_path, "rb") as f:
        data = base64.b64encode(f.read()).decode("utf-8")
    return f"data:{mime};base64,{data}"


def score_color(score: float) -> str:
    """Return a CSS color based on 1-5 score."""
    if score >= 4.5:
        return "#16a34a"  # green
    elif score >= 3.5:
        return "#65a30d"  # lime
    elif score >= 2.5:
        return "#ca8a04"  # amber
    elif score >= 1.5:
        return "#ea580c"  # orange
    else:
        return "#dc2626"  # red


def score_label(score: float) -> str:
    """Return a text label for a 1-5 score."""
    if score >= 4.5:
        return "Excellent"
    elif score >= 3.5:
        return "Good"
    elif score >= 2.5:
        return "Acceptable"
    elif score >= 1.5:
        return "Needs Work"
    else:
        return "Critical"


def priority_color(priority: str) -> str:
    """Return a CSS color for P0-P3 priority."""
    return {
        "P0": "#dc2626",
        "P1": "#ea580c",
        "P2": "#ca8a04",
        "P3": "#65a30d",
    }.get(priority, "#6b7280")


def priority_label(priority: str) -> str:
    """Return a text label for P0-P3 priority."""
    return {
        "P0": "Critical",
        "P1": "High",
        "P2": "Medium",
        "P3": "Low",
    }.get(priority, priority)


def lens_icon(lens: str) -> str:
    """Return a unicode icon for LIFT model lenses."""
    return {
        "clarity": "&#128269;",
        "relevance": "&#127919;",
        "friction": "&#9888;&#65039;",
        "anxiety": "&#128274;",
        "urgency": "&#9201;",
        "technical": "&#9881;&#65039;",
    }.get(lens, "&#128300;")


def report_header_html(title: str, meta_line: str, overall_score: float, pages_count: int, findings_count: int) -> str:
    """Generate the standard Clips OS report header HTML."""
    sc = score_color(overall_score)
    sl = score_label(overall_score)
    return f"""<header>
        <h1>{title}</h1>
        <div class="meta">{meta_line}</div>
        <div class="overall-score">
            <span class="big-score" style="color:{sc};">{overall_score:.1f}<span style="font-size:1.2rem;opacity:0.7;">/5</span></span>
            <div class="score-context">
                <strong>Overall Score</strong><br>
                {sl} — {pages_count} pages analyzed, {findings_count} findings
            </div>
        </div>
    </header>"""


def report_footer_html(skill_name: str) -> str:
    """Generate the standard Clips OS report footer HTML."""
    return f"""<footer>
        <p>Generated by Clips OS {skill_name} &bull; Framework: LIFT Model + Baymard Heuristics &bull; Scoring: 1-5 scale</p>
        <p>Scores reflect analysis at time of audit. Results may vary with traffic source, user segment, and device.</p>
    </footer>"""
